### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by gbjnewman** [manzeloth/live-server#2]
The readme says live-server is under MIT license, but doesn't explicitly state the license of this project.

**Comment by manzeloth** [comment]
Sorry for the confusion. This project had no license until now. I merely adapted the **npm package** [live-server](https://www.npmjs.com/package/live-server) (which is under the MIT license) to work with Vim/Nvim. I read the License section of the package website and I think I am required to include the copyright notice (although I am not really sure because I am not modifying the original package, but just in case).
